# -*- coding: utf-8 -*-
"""py342_馮定一_hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14z3OIaGZ75eKG2QGMviTCJzJPyzrUl-g
"""

n = int (input ('Please input n:'))
for i in range(1, n+1):
           for j in range (1, n+1):
                print(i , "*", j ,"=", i*j)

n = int (input ('Please input n:'))
i = 1
while 1<= i < n+1:
    i in range(1, n+1)
    j = 1
    while 1<= j < n+1:
        j in range (1, n+1)
        print(i , "*", j ,"=", i*j)
        j += 1
    i += 1

