# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vj9p_P3OjPtDEyT-KC5AT_VssfCxdsTM
"""

ans = '1.中文名字: 馮定一.\n2.學號: pyt342118.\n3.以前有寫過程式嗎? 沒有.\n4.想學python的原因或是想用python來做什麼? 學Python fintech的應用.'
print(ans)