# -*- coding: utf-8 -*-
"""py342_馮定一_hw7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jE36SmVNrD_RQYVU3eZCYnR7gcASdIAf
"""

import requests
from bs4 import BeautifulSoup
req = requests.get('https://movies.yahoo.com.tw/movieinfo_main/%E9%A6%B4%E9%BE%8D%E9%AB%98%E6%89%8B3-how-to-train-your-dragon-3-8350'
)
html = req.content.decode('utf8')
soup = BeautifulSoup(html, 'lxml')


for n in soup.select_one('div.movie_intro_info_r'):
  print(n.string)
print(soup.select_one('div.movie_intro_list'))
    
#print(soup.find('h1').string  )
#print(soup.select_one('h3').string  )
#intro = soup.select_one('div.movie_intro_info_r')
#print(intro.span.string)
#print(soup.findAll('span'))